from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    OK = "OK"

    # Input/config
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    MISSING_INPUT_JSON = "MISSING_INPUT_JSON"
    GROUND_TRUTH_NOT_FOUND = "GROUND_TRUTH_NOT_FOUND"
    MODEL_MISSING = "MODEL_MISSING"
    CONFIG_MISSING = "CONFIG_MISSING"
    INVALID_CONFIG = "INVALID_CONFIG"
    INVALID_MANIFEST = "INVALID_MANIFEST"
    INVALID_TOPOLOGY = "INVALID_TOPOLOGY"
    INVALID_VIDEO = "INVALID_VIDEO"
    VIDEO_OPEN_FAILED = "VIDEO_OPEN_FAILED"

    # Detection
    NO_PERSON_DETECTED = "NO_PERSON_DETECTED"
    LOW_DETECTION_CONFIDENCE = "LOW_DETECTION_CONFIDENCE"

    # Tracking
    UNCONFIRMED_TRACK = "UNCONFIRMED_TRACK"
    TRACK_FRAGMENTED = "TRACK_FRAGMENTED"
    NO_MATCHED_TRACK = "NO_MATCHED_TRACK"
    SHORT_TRACK_WINDOW = "SHORT_TRACK_WINDOW"

    # Pose
    LOW_KEYPOINT_VISIBILITY = "LOW_KEYPOINT_VISIBILITY"
    POSE_JITTER = "POSE_JITTER"
    INVALID_BBOX = "INVALID_BBOX"

    # Face
    NO_FACE = "NO_FACE"
    FACE_TOO_SMALL = "FACE_TOO_SMALL"
    FACE_BLURRY = "FACE_BLURRY"
    FACE_SPOOF_RISK = "FACE_SPOOF_RISK"
    ANTI_SPOOF_DISABLED = "ANTI_SPOOF_DISABLED"

    # ReID/Topology
    BODY_OCCLUDED = "BODY_OCCLUDED"
    TOPOLOGY_CONFLICT = "TOPOLOGY_CONFLICT"
    TIME_WINDOW_CONFLICT = "TIME_WINDOW_CONFLICT"
    MULTI_CANDIDATE_CONFLICT = "MULTI_CANDIDATE_CONFLICT"
    NO_REID_CANDIDATE = "NO_REID_CANDIDATE"

    # Pipeline
    STEP_FAILED = "STEP_FAILED"
    EVALUATION_SKIPPED_NO_GT = "EVALUATION_SKIPPED_NO_GT"


def as_reason(code: ErrorCode | str) -> str:
    value = code.value if isinstance(code, ErrorCode) else str(code)
    known = {item.value for item in ErrorCode}
    return value if value in known else ErrorCode.STEP_FAILED.value
